# Generated by Django 3.2 on 2022-07-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmigrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=500, unique=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='api_key',
            field=models.CharField(default='', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ApiToken',
        ),
        migrations.AddField(
            model_name='session',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmigrations.client'),
        ),
    ]
