# Generated by Django 3.2 on 2022-08-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmigrations', '0003_remove_session_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationEmailLinkEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmigrations.client')),
            ],
            options={
                'db_table': 'verification_email_link_entry',
            },
        ),
    ]
