# Generated by Django 3.2 on 2022-04-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmigrations', '0003_auto_20220412_1421'),
        ('appmigrations', '0003_auto_20220412_1453'),
    ]

    operations = [
    ]
