# Generated by Django 3.2 on 2022-04-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmigrations', '0004_merge_0003_auto_20220412_1421_0003_auto_20220412_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowOwner',
            new_name='ShopOwner',
        ),
    ]
