# Generated by Django 3.2 on 2022-04-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmigrations', '0005_rename_showowner_shopowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appmigrations.shopowner'),
        ),
    ]
